-- ============================================
-- INSERT LEZIONI - MusicAll  
-- TODO: Da completare
-- ============================================

-- ⚠️ FILE PLACEHOLDER
-- Questo file verrà popolato eseguendo:
-- php tests/generate_lezioni_from_excel.php
--
-- Il generatore creerà automaticamente tutte le INSERT
-- associando allievi del file Excel a docenti/materie
-- basandosi sulla mappatura in database/orari_docenti.md
--
-- Database attualmente popolato con:
-- ✅ 25 Docenti + 28 relazioni docenti-materie  
-- ✅ 220 Allievi
-- ✅ 6 Aule
-- ✅ 18 Materie
-- ============================================