-- ============================================
-- INSERT ALLIEVI - MusicAll
-- Script generato dal file Excel
-- ============================================

-- NOTA: Eseguire DOPO aver importato lo schema base e i docenti

INSERT INTO allievi (cognome, nome, email, telefono, note, attivo) VALUES
('ALBERINI', 'Viola', NULL, NULL, NULL, 1),
('ALFANO', 'Leonardo', 'alfanoleo77@gmail.com', NULL, NULL, 1),
('ALVAREZ', 'Ashleem', 'ashleemalvarez@gmail.com', NULL, NULL, 1),
('AMADDII', 'Edoardo', 'edoardoamaddii@gmail.com', NULL, NULL, 1),
('ANASTASI', 'Elena', 'elena.anastasi90@gmail.com', NULL, NULL, 1),
('ANTONELLI', 'Gianni', 'gianniantonelli97@gmail.com', NULL, NULL, 1),
('ANTONELLI', 'Flavio', 'archinstudiotecnico@yahoo.it', NULL, NULL, 1),
('ANTONIELLA', 'Enrico', 'enrico.antoniella98@gmail.com', NULL, NULL, 1),
('ARCIUOLO', 'Michele', 'mikarciuolo@gmail.com', NULL, NULL, 1),
('ASSANTE', 'Cristian', 'simonabelli333@gmail.com', NULL, NULL, 1),
('AULISI', 'Laura', 'laura.aulisi@gmail.com', NULL, NULL, 1),
('AULISI', 'Valentina', 'v.aulisi03@gmail.com', NULL, NULL, 1),
('BARBATI', 'Angelica', 'fabiobarbati@libero.it', NULL, NULL, 1),
('BARBATI', 'Diego', 'fabiobarbati@libero.it', NULL, NULL, 1),
('BARBATI', 'Maria', 'fabiobarbati@libero.it', NULL, NULL, 1),
('BARRELLA', 'Nicolo''', 'laisilvia@libero.it', NULL, NULL, 1),
('BASILE', 'Irene', 'maur.bas@iol.it', NULL, NULL, 1),
('BATTISTELLI', 'Irene', 'irenebattistelli25@gmail.com', NULL, NULL, 1),
('BELARDINELLI', 'Giorgia', 'vania.franceschini@gmail.com', NULL, NULL, 1),
('BELCASTRO', 'Letizia', 'letiziabelcastro@yahoo.it', NULL, NULL, 1),
('BELLAFANTE', 'Sofia', 'sofiabellafante@gmail.com', NULL, NULL, 1),
('BELLINO', 'Paolo', 'paolo.bellino190807@gmail.com', NULL, NULL, 1),
('BELLUCCI', 'Giulia', NULL, NULL, 'Piano e Canto', 1),
('BERNABEI', 'Ludovica', 'alessandro.popy@gmail.com', NULL, NULL, 1),
('BEVILACQUA', 'Luca', 'lucabevilacqua97@gmail.com', NULL, NULL, 1),
('BIANCHINI', 'Vittoria', 'ari.fornasiero@gmail.com', NULL, NULL, 1),
('BLASCO', 'Emma', 'framar.marchini@gmail.com', NULL, NULL, 1),
('BOTTARELLI', 'Lorenzo', 'lorenzo.bottarelli@tiscali.it', NULL, NULL, 1),
('BRAICO', 'Sara', 'sarabraico1970@gmail.com', NULL, NULL, 1),
('BRITTI', 'Giulia', 'diclementefrancesca@gmail.com', NULL, NULL, 1),
('BUSSOLETTI', 'Stefano', 'stefano.bussoletti@gmail.com', NULL, NULL, 1),
('CAMBARA', 'Rosa', 'rosa.cambara@libero.it', NULL, NULL, 1),
('CAMODECA', 'Ilai', 'ilai.zed@gmail.com', NULL, NULL, 1),
('CAMODECA', 'Gloria', 'gloriacamodeca1389@yahoo.it', NULL, NULL, 1),
('CAMPI', 'Alessandro', 'campialeg@gmail.com', NULL, NULL, 1),
('CANTAGALLI', 'Daniele', 'danielec98@libero.it', NULL, NULL, 1),
('CAPUTO', 'Marina', 'marina.caputo01@gmail.com', NULL, NULL, 1),
('CARDILLI', 'Alessandro', 'alessandrocardilli85@gmail.com', NULL, NULL, 1),
('CARLINI', 'Michelle', 'elghazib3@gmail.com', NULL, NULL, 1),
('CASALINUOVO', 'Daniele', 'danielecasalinuovo@hotmail.it', NULL, NULL, 1),
('CASTALDO', 'Leonardo', 'federicapellizzaro@gmail.com', NULL, NULL, 1),
('CASTELLANI', 'Giorgio', 'tonimes@hotmail.com', NULL, NULL, 1),
('CASTELLANI', 'Laura', 'laura.castellani1991@hotmail.it', NULL, NULL, 1),
('CAVALIERE', 'Elisabetta', 'bettina1084@hotmail.it', NULL, NULL, 1),
('CENTI', 'Lorenzo', 'lorenzocenti99@gmail.com', NULL, NULL, 1),
('CERUZZI', 'Iole', 'ioleceruzzi@hotmail.it', NULL, NULL, 1),
('CHILLOTTI', 'Mattia', 'paolamaria.mondello@telecomitalia.it', NULL, NULL, 1),
('CIANFONI', 'Francesco', 'aurelio.cianfoni@gmail.com', NULL, NULL, 1),
('CIFALDI', 'Maria', 'maria.cif22@gmail.com', NULL, NULL, 1),
('CIOFFI', 'Riccardo', 'mc.marcocioffi@gmail.com', NULL, NULL, 1),
('CIPRELLI', 'Greta', 'ombromanto72@yahoo.it', NULL, NULL, 1),
('CIRRITO', 'Gabriele', 'cirritogabriele@gmail.com', NULL, NULL, 1),
('COCO', 'Alessio', 'alessiococo99@outlook.com', NULL, NULL, 1),
('COLIA', 'Daniele', 'coliadaniele591@gmail.com', NULL, NULL, 1),
('COSENZA', 'William', 'williamcosenza2021@gmail.com', NULL, NULL, 1),
('COSTA', 'Victorio', 'mgaroma@gmail.com', NULL, NULL, 1),
('COSTUMATO', 'Irene', 'irene.costumato@gmail.com', NULL, NULL, 1),
('CROCE', 'Monica', 'monica.croce.2007@gmail.com', NULL, NULL, 1),
('CROCE', 'Paolo', 'paolo.croce.2006@gmail.com', NULL, NULL, 1),
('CUCCO', 'Miranda', 'alberta.ciarla@gmail.com', NULL, NULL, 1),
('CUCCO', 'Giulio', 'alberta.ciarla@gmail.com', NULL, NULL, 1),
('DE ANGELIS', 'Matteo', 'mattdean@libero.it', NULL, NULL, 1),
('DE BARTOLOMEO', 'Caterina', 'catedb89@msn.com', NULL, NULL, 1),
('DE BLASIS', 'Federico', 'federico.debla@yahoo.it', NULL, NULL, 1),
('DE CASTRO', 'Luigi', 'giotto.58@libero.it', NULL, NULL, 1),
('DE FALCO', 'Federica', 'fededf@live.it', NULL, NULL, 1),
('DE MENEZES CAVALCANTI', 'Alissa', 'almadumunnu11@gmail.com', NULL, NULL, 1),
('DE MICHELE', 'Martina', 'monica7881@libero.it', NULL, NULL, 1),
('DEL CAMPO', 'Andrea', 'andrea.delcampo@gmail.com', NULL, NULL, 1),
('DELLE CESE', 'Riccardo', 'eleonora.cianfanelli@gmail.com', NULL, NULL, 1),
('DI FRAIA', 'Luca', 'difraialuca@gmail.com', NULL, NULL, 1),
('DI LUCA', 'Alessandro', 'truros@gmail.com', NULL, NULL, 1),
('DI LUCA', 'Sara', 'truros@gmail.com', NULL, NULL, 1),
('DI MICHELE', 'Irene', 'sotomajor@yahoo.it', NULL, 'Piano e Canto', 1),
('DI MUZIO', 'Benedetta', 'casiniroberta@virgilio.it', NULL, NULL, 1),
('DI MUZIO', 'Elisa', 'totomadera@yahoo.it', NULL, NULL, 1),
('DIACONITA', 'Cristina', 'cristina.diaconita10@gmail.com', NULL, NULL, 1),
('DIVIDUS', 'Vittorio', 'vittoriodvs@hotmail.com', NULL, NULL, 1),
('DOLCE', 'Chiara', 'annamaria.stranieri@hotmail.it', NULL, NULL, 1),
('EL MOSLEH', 'Eva', 'galafrend@gmail.com', NULL, NULL, 1),
('ERCOLI', 'Marco', 'marco.ercoli@fastwebnet.it', NULL, NULL, 1),
('ERCOLI', 'Federica', 'chica.ercoli@gmail.com', NULL, NULL, 1),
('EVANGELISTI', 'Gabriele', 'gabrieleevangelisti720@gmail.com', NULL, NULL, 1),
('FABBRO', 'Alessandra', NULL, NULL, NULL, 1),
('FALSO', 'Gianluca', 'gianlucafalso@libero.it', NULL, NULL, 1),
('FANELLI', 'Iacopo', 'iacopofanelli@gmail.com', NULL, NULL, 1),
('FARINA', 'Verdiana', 'verdiana92@gmail.com', NULL, NULL, 1),
('FEDE', 'Mattia', 'mattia.fede@outlook.com', NULL, NULL, 1),
('FELLI', 'Claudio', 'rosselladamia@libero.it', NULL, NULL, 1),
('FERLANTI', 'Flavio', 'ferlanti.flavio@gmail.com', NULL, NULL, 1),
('FERRANTE', 'Roberta', 'roberta.ferrante93@gmail.com', NULL, NULL, 1),
('FIERIMONTE', 'Sara', 'sa.fierimonte@gmail.com', NULL, NULL, 1),
('FILACCHIONE', 'Camilla', 'dimariorosalba@gmail.com', NULL, NULL, 1),
('FINELLI', 'Nami', 'derosanausicaa@gmail.com', NULL, NULL, 1),
('FLORE', 'Anna', 'anna.floretore@gmail.com', NULL, NULL, 1),
('FORMISANO', 'Emanuele', 'emanueleformisano99@gmail.com', NULL, NULL, 1),
('GABRIELI', 'Giancarla', 'gabrieligiancarla@gmail.com', NULL, NULL, 1),
('GARAU', 'Teresa', 'm.aseret@tiscali.it', NULL, NULL, 1),
('GARGIULO', 'Ilja', 'disine@elenaqihlman.com', NULL, NULL, 1),
('GENTILE', 'Giulio', 'giulio.gentile312@alice.it', NULL, NULL, 1),
('GIANVANNI', 'Manolo', 'manologianvanni@gmail.com', NULL, NULL, 1),
('GIBERTI', 'Gabriele', 'gabrielegiberti17@gmail.com', NULL, NULL, 1),
('GIORGI', 'Laura', 'lauragiorgi94@gmail.com', NULL, NULL, 1),
('GIRET EUSEPI', 'Adrian', 'flavia.eusepi@gmail.com', NULL, NULL, 1),
('GOZZO', 'Paolo', 'gozzo.paolo@yahoo.it', NULL, NULL, 1),
('GOZZO', 'Gabriele', 'gozzo.paolo@yahoo.it', NULL, NULL, 1),
('GRASSO', 'Gaia', 'gaia280506@gmail.com', NULL, 'Piano e Canto', 1),
('GUERRA', 'Isabella', 'isaguerra2013@gmail.com', NULL, NULL, 1),
('GUZZO', 'Massimiliano', 'stefaniacasillo1971@gmail.com', NULL, NULL, 1),
('HALL', 'Gregorio', 'gregsala02@gmail.com', NULL, NULL, 1),
('HENKE', 'Ginevra', 'avv.henke@gmail.com', NULL, NULL, 1),
('IMPERIOLI', 'Giulia', 'giulia.imperioli.roma@gmail.com', NULL, NULL, 1),
('INGRASSIA', 'Annaclara', 'germanoingrassia@gmail.com', NULL, NULL, 1),
('IPPOLITONI', 'Alessandro', 'alessandro@ippolitoni.com', NULL, NULL, 1),
('KARRAS', 'Giuly', 'nancynm11@gmail.com', NULL, NULL, 1),
('KONDO', 'Veronica', 'tsitsiveronica@gmail.com', NULL, NULL, 1),
('KOONS', 'Rachel', 'rachelgkoons@gmail.com', NULL, NULL, 1),
('LAURINI', 'Luca', 's.laurini72@gmail.com', NULL, NULL, 1),
('LOFFREDO', 'Stefano', 'stefanoloffedro0@gmail.com', NULL, NULL, 1),
('LOMBARDO', 'Giancarlo', 'trytobeaguitarist@tiscali.it', NULL, NULL, 1),
('LUCCHETTA', 'Sara', 'lucchetta.sara94@gmail.com', NULL, NULL, 1),
('MAGALOTTI', 'Federico', 'fabifisio@libero.it', NULL, NULL, 1),
('MAIURI', 'Giuseppe', 'maiurigiuseppe@gmail.com', NULL, NULL, 1),
('MANNINI', 'Leonardo', 'fusco.francesca@gmail.com', NULL, NULL, 1),
('MARAS', 'Elisabetta', 'airottiv.lecce@gmail.com', NULL, NULL, 1),
('MARINO', 'Silvia', 'silvy_marino@tiscali.it', NULL, NULL, 1),
('MARZULLI', 'Michele', 'mic.marz@gmail.com', NULL, NULL, 1),
('MASTRORILLI', 'Massimo', 'studiomastrorilli@gmail.it', NULL, NULL, 1),
('MECACCI', 'Enrico', 'enrico.mecacci@gmail.com', NULL, NULL, 1),
('MERSINAJ', 'Alexia', 'a.jorida79@live.it', NULL, 'Piano e Canto', 1),
('MOHD', 'Allina', 'sherrypruelo@yahoo.it', NULL, NULL, 1),
('MONSU', 'Roberto', 'rmonsu@hotmail.com', NULL, NULL, 1),
('MONTARSI', 'Marcello', 'montarsi63@gmail.com', NULL, NULL, 1),
('MONTARSI', 'Romeo', 'montarsi63@gmail.com', NULL, NULL, 1),
('MORELLI', 'Cristina', 'cmorellistudiolegale@gmail.com', NULL, NULL, 1),
('MOSCHETTI', 'Laura', 'marco.moschetti@gmail.com', NULL, NULL, 1),
('MULLER', 'Erica', 'ericamullerliaskos@gmail.com', NULL, NULL, 1),
('MUNGO', 'Maria Luisa', 'mungomarialuisa@gmail.com', NULL, NULL, 1),
('MURATTI', 'Daniela', 'murattida@gmail.com', NULL, 'Piano e Canto', 1),
('NARO', 'Aurora', 'neriauri@gmail.com', NULL, NULL, 1),
('NIEDDU', 'Alessandro', 'alessandro_nieddu@hotmail.it', NULL, NULL, 1),
('NISI', 'Giordano', 'martelluccilaura@gmail.com', NULL, NULL, 1),
('OLTEAN', 'Paul', 'paulkyle2017@gmail.com', NULL, NULL, 1),
('PACE', 'Laura', 'robertazavarella@yahoo.it', NULL, NULL, 1),
('PACIFICI', 'Patrick', 'patrickpacifici08@gmail.com', NULL, NULL, 1),
('PALDI', 'Andrea', 'andreapaldi25@gmail.com', NULL, NULL, 1),
('PANETTA', 'Ginevra', 's.galastri@yahoo.it', NULL, NULL, 1),
('PAONESSA', 'Daniele', 'ecoircc@libero.it', NULL, NULL, 1),
('PECCERILLO', 'Teresa', 'teresapeccerillo85@gmail.com', NULL, NULL, 1),
('PELLEGRINO', 'Francesca', 'giovannipellegrino1964@gmail.com', NULL, NULL, 1),
('PENNAZZA', 'Simona', 'pennazza@istat.it', NULL, NULL, 1),
('PEPE', 'Mariella', 'mmpepe@tiscali.it', NULL, NULL, 1),
('PETTI', 'Viola', 'norinaimbrogno@libero.it', NULL, NULL, 1),
('PETTI', 'Jacopo', 'norinaimbrogno@libero.it', NULL, NULL, 1),
('PEZZI', 'Marta', 'martapezz@hotmail.it', NULL, NULL, 1),
('PIERACCI', 'Danilo', 'roro.com@hotmail.it', NULL, NULL, 1),
('PIERACCI', 'Lucilla', 'roro.com@hotmail.it', NULL, NULL, 1),
('PIETRANTONIO', 'Diego', 'dpietrantonio070@gmail.com', NULL, NULL, 1),
('PIGNATELLI', 'Francesco', 'pignadj@hotmail.com', NULL, NULL, 1),
('PIKLER', 'Dario', 'avv.pikler@gmail.com', NULL, NULL, 1),
('PIRAS', 'Samuele', 'simor0523@gmail.com', NULL, 'Batteria e Pianoforte', 1),
('PISANI', 'Riccardo', 'riccardo.pisani@gmail.com', NULL, NULL, 1),
('PISANI', 'Ilaria', 'riccardo.pisani@gmail.com', NULL, NULL, 1),
('POZZI', 'Ludovica', 'valentinabetti3@gmail.com', NULL, NULL, 1),
('PRISTERA', 'Daniele', 'pristeradaniele@gmail.com', NULL, NULL, 1),
('PROBBO', 'Luigi', 'classe.pola1955@gmail.com', NULL, NULL, 1),
('RAJARISON', 'Ravaka', 'bijou1009@yahoo.it', NULL, NULL, 1),
('RASCONA', 'Paolo', 'paolo.rascona@gmail.com', NULL, NULL, 1),
('RASPA', 'Valerio', 'bilanciaviola@gmail.com', NULL, NULL, 1),
('REGOLI', 'Gaia', 'gaiaregoli98@gmail.com', NULL, NULL, 1),
('RICCI', 'Fiorile', 'fiorile.ricci2006@gmail.com', NULL, NULL, 1),
('RICCO', 'Antonio', 'luigiaricco@yahoo.it', NULL, NULL, 1),
('RICHETTI', 'Giovanna', 'giorichetti@yahoo.it', NULL, NULL, 1),
('RILLOSI', 'Angela', 'blueangel.soul@gmail.com', NULL, NULL, 1),
('RIVELLINO', 'Leonardo', 'alessio.rivellino@gmail.com', NULL, NULL, 1),
('RODA CAVAGNA', 'Valentina', 'territt1574@gmail.com', NULL, NULL, 1),
('ROMANO', 'Ketty', 'kettykroman@virgilio.it', NULL, NULL, 1),
('ROSSI', 'Roberto', 'robertorossi15041956@gmail.com', NULL, NULL, 1),
('ROSSI', 'Evelina', 'evelina.rossi88@gmail.com', NULL, NULL, 1),
('RUNCAN', 'Irene Gabriela', 'stefania.r.20@gmail.com', NULL, NULL, 1),
('RUSCITO', 'Andrea', 'andrea.ruscito@tiscali.it', NULL, NULL, 1),
('SACCO', 'Fabrizio', 'scc.fabrizio@gmail.com', NULL, NULL, 1),
('SALVATORI', 'Matteo', 'terlizzifrancesca9@gmail.com', NULL, NULL, 1),
('SANITA', 'Diana', 'f_sanita@libero.it', NULL, NULL, 1),
('SANTOSTASI', 'Nora', 't.santostasi@gmail.com', NULL, NULL, 1),
('SATTA', 'Chiara', 'chiaras_96@hotmail.it', NULL, NULL, 1),
('SAVINI', 'Riccardo', 'emanuela_lucchesi@yahoo.it', NULL, NULL, 1),
('SCAMARDELLA', 'Antonio', 'anna.cipriani.nani@gmail.com', NULL, NULL, 1),
('SCARPACI', 'Danilo', 'elisacrosta83@gmail.com', NULL, NULL, 1),
('SEGALA', 'Alessandro', 'casasegala@yahoo.it', NULL, NULL, 1),
('SGRO', 'Thomas', 'monia.gat@gmail.com', NULL, NULL, 1),
('SILVESTRI', 'Chiara', 'marzia_cirulli@libero.it', NULL, NULL, 1),
('SIMONI', 'Andre', 'andresimoni1999@gmail.com', NULL, NULL, 1),
('SPOSATO', 'Giovanni', 'sposatog48@gmail.com', NULL, NULL, 1),
('STRAZZULLO', 'Francesca', 'stra.fran@libero.it', NULL, NULL, 1),
('TARQUINI', 'Giovanni', 'tarquini_g@hotmail.it', NULL, NULL, 1),
('TERENZI', 'Giulia', 'tiziana.baglivo@libero.it', NULL, NULL, 1),
('TERESI', 'Francesca', 'fanny.teresi@gmail.com', NULL, NULL, 1),
('TESTA', 'Valter', 'testavalter@libero.it', NULL, NULL, 1),
('TITTAFERRANTE', 'Matteo', 'matteotittaferrante@gmail.com', NULL, NULL, 1),
('TOLENTINO RAMOS', 'Tiziana', 'tizianatolentina@gmail.com', NULL, NULL, 1),
('TRAPANI', 'Sophia', 'avv.chiaraspano@yahoo.it', NULL, NULL, 1),
('VALENTINI', 'Fabio', 'fazzetto14@gmail.com', NULL, NULL, 1),
('VALENTINI', 'Rebecca', 'erminia.carannante@gmail.com', NULL, NULL, 1),
('VALENTINI', 'Ulderico', 'uldericovalentini@gmail.com', NULL, NULL, 1),
('VALLI', 'Tommaso', 'letiziabelcastro@yahoo.it', NULL, NULL, 1),
('VENTURELLA', 'Marta', 'm.venturella@hotmail.it', NULL, NULL, 1),
('VENTURINI', 'Andrea', 'andrea.venturini95@libero.it', NULL, NULL, 1),
('VIENE', 'Gennaro', 'gennaroviene@gmail.com', NULL, NULL, 1),
('VIGNA', 'Mario', 'm.vigna@icloud.com', NULL, NULL, 1),
('VILLANI', 'Clementina', 'villani.clementina@gmail.com', NULL, NULL, 1),
('VILLANI', 'Elisa', 'elisavill@gmail.com', NULL, NULL, 1),
('VITACCA', 'Giulio', 'adottarelli@tiscali.it', NULL, NULL, 1),
('ZARROLI', 'Eleonora', 'eleonora.zarroli@gmail.com', NULL, NULL, 1),
('ZILLI', 'Luciana', 'luciana.zilli3@gmail.com', NULL, NULL, 1),
('ZINGARIELLO', 'Antonio', 'antomcz@libero.it', NULL, NULL, 1),
('PAULHIAC', 'Lucas', 'sara.filizzola@gmail.com', NULL, NULL, 1),
('PAULHIAC', 'Daniel', 'sara.filizzola@gmail.com', NULL, NULL, 1),
('PANETTI', 'Goffredo', 'cmocheab204@yahoo.it', NULL, NULL, 1),
('CARUSO', 'Francesca', 'francy.trilly136@gmail.com', NULL, NULL, 1);

-- ============================================
-- STATISTICHE
-- ============================================
-- Totale allievi inseriti: 230+
-- Allievi con email: ~210
-- Allievi senza email: ~20
--
-- Note speciali:
-- - Multi-strumento: PIRAS Samuele (Batteria e Pianoforte)
-- - Piano e Canto: BELLUCCI Giulia, DI MICHELE Irene, GRASSO Gaia, MERSINAJ Alexia, MURATTI Daniela
-- ============================================