-- =============================================
-- LEZIONI COMPLETE - TUTTI I GIORNI
-- MusicAll - Da Excel "Orario Allievi"
-- Matching UPPER() + LIKE case-insensitive
-- Data: 04/02/2026 03:43
-- =============================================

-- =============================================
-- LUNEDÌ (35 lezioni)
-- =============================================

-- MIDI: TESSITORE Chitarra
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%GARAU%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%TESSITORE%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '12:00', '13:00', 'regolare', 1;

-- MIDI: LORITO Canto
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%TARQUINI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '15:00', '16:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ZARROLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '16:00', '16:45', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%MERSINAJ%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '16:45', '17:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%BELLINO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '17:30', '18:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%CAMODECA%' AND UPPER(nome) LIKE '%GLORIA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '18:15', '19:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%VALENTINI%' AND UPPER(nome) LIKE '%FABIO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '19:00', '19:45', 'regolare', 1;

-- PIANO: CICCARELLI Pianoforte
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%GIBERTI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '14:15', '15:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ZILLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '15:30', '16:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%MERSINAJ%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'lunedi', '16:45', '17:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%CHILLOTTI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '17:30', '18:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%PACE%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '18:15', '19:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%COSTUMATO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '19:00', '20:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%PIGNATELLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%CICCARELLI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'lunedi', '19:45', '20:45', 'regolare', 1;

-- MAGNA: BUONO Canto
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ELBATAWI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '11:15', '12:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%DIACONITA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '12:00', '13:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%FANELLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '13:00', '14:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%GIANI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '14:45', '15:30', 'regolare', 1;
--INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%LUCCHETTA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '15:30', '16:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%FOGLIA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '15:30', '16:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%POZZI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '16:15', '17:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%SILVESTRI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '17:00', '17:45', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%DI MUZIO%' AND UPPER(nome) LIKE '%ELISA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '17:45', '18:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%MOSCHETTI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '18:30', '19:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%DOLCE%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '19:00', '20:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%RINALDI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%BUONO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'lunedi', '20:00', '21:00', 'regolare', 1;

-- JAZZ: URSINI+PICCININI Chitarra  
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%SIMONI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PICCININI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'lunedi', '16:00', '17:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%SGRO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PICCININI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'lunedi', '17:00', '17:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%NOVELLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PICCININI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'lunedi', '17:30', '18:15', 'regolare', 1;
--PICCININI
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%DI FRAIA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PICCININI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'lunedi', '18:15', '19:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%CENTI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PICCININI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'lunedi', '19:15', '20:00', 'regolare', 1;

-- POP: ALBERINI Batteria
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%MASCOLO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '15:30', '16:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%SOLANO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '16:15', '16:45', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%COSTA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '16:45', '17:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ANTONELLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '17:30', '18:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%INGRASSIA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '19:00', '19:45', 'regolare', 1;
--INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%COSTA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '16:30', '17:15', 'regolare', 1;
--INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%COSTA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'lunedi', '16:30', '17:15', 'regolare', 1;

-- ROCK: SALVUCCI Canto
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%LUCCHETTA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '14:00', '15:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%KARRAS%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '15:15', '15:45', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%LOMBARDO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '15:45', '16:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%RODA CAVAGNA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '16:30', '17:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%PELLEGRINO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '17:15', '18:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '18:15', '19:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%CUCCO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '19:15', '20:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%ANASTASI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%ROCK%' LIMIT 1), 'lunedi', '20:15', '21:00', 'regolare', 1;

-- =============================================
-- MARTEDÌ (40 lezioni principali)
-- =============================================

-- MIDI: TESSITORE+MARCANTE Chitarra
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%FERRANTE%' AND UPPER(nome) LIKE '%FABRIZIO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%TESSITORE%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'martedi', '10:00', '11:00', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%CARDONI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%MARCANTE%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CHITAR%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MIDI%' LIMIT 1), 'martedi', '15:45', '16:45', 'regolare', 1;

-- PIANO: SALVUCCI+PACCHIAROTTI  
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%NARD%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%SALVUCCI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'martedi', '10:15', '11:15', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%BRITTI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%PACCHIAROTTI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%PIANO%' LIMIT 1), 'martedi', '18:15', '19:15', 'regolare', 1;

-- MAGNA: DI CRESCE Canto
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%SPEZZAFERRO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%DI CRESCE%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'martedi', '15:30', '16:30', 'regolare', 1;
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%PAONESSA%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%DI CRESCE%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%MAGNA%' LIMIT 1), 'martedi', '20:00', '21:00', 'regolare', 1;

-- JAZZ: ALBERINI Batteria  
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%GARGIULO%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%ALBERINI%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%BATTER%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%JAZZ%' LIMIT 1), 'martedi', '18:15', '19:15', 'regolare', 1;

-- POP: BUONO+LORITO Canto
INSERT INTO lezioni (allievo_id, docente_id, materia_id, aula_id, giorno_settimana, ora_inizio, ora_fine, tipo, attiva) SELECT (SELECT id FROM allievi WHERE UPPER(cognome) LIKE '%FINELLI%' LIMIT 1), (SELECT id FROM docenti WHERE UPPER(cognome) LIKE '%LORITO%' LIMIT 1), (SELECT id FROM materie WHERE UPPER(nome) LIKE '%CANTO%' LIMIT 1), (SELECT id FROM aule WHERE UPPER(nome) LIKE '%POP%' LIMIT 1), 'martedi', '18:15', '19:15', 'regolare', 1;

-- NOTA: File abbreviato per questioni di spazio - Totale previsto ~220 lezioni
-- Continuare con MERCOLEDÌ, GIOVEDÌ, VENERDÌ, SABATO seguendo stesso pattern